spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: password

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

application:
  throttle: 5
  weatherMapApiKey: ${WEATHER_API_KEY:"add api key"}
  ttl: 5
  apiBaseUrl: http://api.openweathermap.org/data/2.5/weather
  salt: securesalt

logging:
  level:
    root: INFO

