spring:
  datasource:
    url: jdbc:h2:file:./h2-db/weather
  h2:
    console:
      enabled: true

application:
  throttle: 5
  weatherMapApiKey: ${WEATHER_API_KEY:"add api key"}
  ttl: 5
  apiBaseUrl: http://api.openweathermap.org/data/2.5/weather
  salt: securesalt


