spring:
  jpa:
    hibernate:
      ddl-auto: update



  datasource:
    url: jdbc:h2:file:./h2-db/weather;IGNORECASE=TRUE
    username: sa
    password: password
    hikari:
      auto-commit: true

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: ${INIT_MODE:never}

application:
  throttle: 5
  weatherMapApiKey: add api key
  ttl: 5
  apiBaseUrl: http://api.openweathermap.org/data/2.5/weather
  salt: securesalt

logging:
  level:
    root: INFO

